const ENDPOINT = process.env.IS_NOSE_ENDPOINT || `https://img-svc.apps.hbp.eu/api`
const PKG_NAME = `is-nose`
const REPO_URL = `https://github.com/xgui3783/is-nose.git`
const VER = `0.0.1`

module.exports = {
  ENDPOINT,
  AGENT: ` - generated by ${PKG_NAME}=${VER}<${REPO_URL}>`
}